#!/usr/bin/env python3
"""
Wait for a vel_grid_full_summary.json file, run plotting, and write a short markdown report.

Usage: python scripts/finalize_vel_grid_run.py --summary plots/vel_grid_full_relaxed/vel_grid_full_summary.json
"""
import argparse
import json
import os
import subprocess
import time


def wait_for_file(path, poll_s=30):
    print('Watching for', path)
    while not os.path.exists(path):
        time.sleep(poll_s)
    print('Found', path)


def run_plot(summary_path):
    print('Running summary plot')
    cmd = ['python3', 'scripts/plot_vel_grid_summary.py', '--summary', summary_path]
    subprocess.run(cmd, check=True)
    print('Plots done')


def write_report(summary_path, out_md=None):
    s = json.load(open(summary_path))
    out_md = out_md or os.path.join(os.path.dirname(summary_path), 'vel_grid_full_report.md')
    lines = []
    lines.append('# Velocity-grid full run report')
    lines.append('')
    lines.append('Summary of per-velocity counts and nearest-center stats:')
    lines.append('')
    lines.append('|velocity|n_total|lsq_count|intersection_count|lsq_mean_center_km|lsq_median_center_km|inter_mean_center_km|inter_median_center_km|')
    lines.append('|--:|--:|--:|--:|--:|--:|--:|--:|')
    for v in sorted(s.keys(), key=lambda x: float(x)):
        row = s[v]
        counts = row.get('counts', {})
        lsq = counts.get('lsq_2array', 0) + counts.get('lsq_multi', 0)
        inter = sum(n for k,n in counts.items() if k.startswith('intersection'))
        lines.append(f"|{v}|{row.get('n_total',0)}|{lsq}|{inter}|{row.get('lsq_mean_center_km',''):.2f}|{row.get('lsq_median_center_km',''):.2f}|{row.get('inter_mean_center_km',''):.2f}|{row.get('inter_median_center_km',''):.2f}|")

    lines.append('')
    lines.append('## Notes')
    lines.append('- This report was autogenerated by `scripts/finalize_vel_grid_run.py`.')
    lines.append('- Plots created: `vel_grid_counts.png`, `vel_grid_center_means.png` in the same folder as the summary.')

    with open(out_md, 'w') as fh:
        fh.write('\n'.join(lines))
    print('Wrote report to', out_md)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--summary', required=True, help='Path to vel_grid_full_summary.json to wait for')
    args = parser.parse_args()

    wait_for_file(args.summary)
    run_plot(args.summary)
    write_report(args.summary)


if __name__ == '__main__':
    main()
